media: assets
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts/posts
    fields:
      - name: title
        label: Title
        type: string
      - name: permalink
        label: Permalink
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: YYYY-MM-DDTHH:mm:ssZ
      - name: layout
        label: Layout
        type: string
        default: post
        hidden: true
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: published
        label: Published
        type: boolean
        default: false
      - name: type
        label: Type
        type: string
        default: post
        hidden: true
      - name: body
        label: Body
        type: rich-text
  - name: notes
    label: Notes
    type: collection
    path: _posts/notes
    fields:
      - name: title
        label: Title
        type: string
      - name: permalink
        label: Permalink
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: YYYY-MM-DDTHH:mm:ssZ
      - name: layout
        label: Layout
        type: string
        default: post
        hidden: true
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: published
        label: Published
        type: boolean
        default: false
      - name: type
        label: Type
        type: string
        default: note
        hidden: true
      - name: body
        label: Body
        type: rich-text
  - name: journal
    label: Journal
    type: collection
    path: _posts/journal
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: YYYY-MM-DDTHH:mm:ssZ
      - name: published
        label: Published
        type: boolean
        default: false
      - name: type
        label: Type
        type: string
        default: journal
        hidden: true
      - name: body
        label: Body
        type: rich-text
