media: assets
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    fields:
      - name: title
        label: Title
        type: string
      - name: permalink
        label: Permalink
        type: string
      - name: date
        label: Date
        type: date
      - name: layout
        label: Layout
        type: string
        default: post
        hidden: true
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: type
        label: Type
        type: select
        options:
          values: [ post, note ]
      - name: body
        label: Body
        type: rich-text