title: Mitja Felicijan
author: Mitja Felicijan
email: mitja.felicijan@gmail.com
url: https://mitjafelicijan.com
lang: en

description: >-
  You do not learn by relaxing. You learn by violently assaulting your problem
  until it surrenders its mysteries to you.

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-seo-tag

jekyll-minifier:
  uglifier_args:
    harmony: true
