title: "Mitja Felicijan"
baseurl: "https://mitjafelicijan.com"
description: "You do not learn by relaxing. You learn by violently assaulting your problem until it surrenders its mysteries to you."
language: "en-us"

# Code highlighting.
# https://swapoff.org/chroma/playground/
highlighting: vs

# Minifies output HTML (including inline CSS, JS).
minify: true

# Other generaters, in this case RSS generator.
extras:
  - template: feed.xml
    url: feed.xml
  - template: robots.txt
    url: robots.txt
  - template: sitemap.xml
    url: sitemap.xml
  - template: 404.html
    url: 404.html
