title: "Mitja Felicijan"
baseurl: "https://mitjafelicijan.com"
description: "You do not learn by relaxing. You learn by violently assaulting your problem until it surrenders its mysteries to you."
language: "en-us"

# Code highlighting.
# https://swapoff.org/chroma/playground/
highlighting: "vs"

# Minifies output HTML (including inline CSS, JS).
minify: true

extras:
  - template: index.xml
    url: index.xml
  - template: notes.xml
    url: notes.xml
  - template: robots.txt
    url: robots.txt
  - template: sitemap.xml
    url: sitemap.xml
  - template: radio.pls
    url: radio.pls
